Email_Notification/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
registrations: 'registrations'
 }
    #setting routes for each button created.
    match 'users/mail' => 'users#mail', :as => :mail, via: :post
    match 'users/sendall' => 'users#sendall', :as => :sendall, via: :get
    match 'users/sendloc' => 'users#sendloc', :as => :sendloc, via: :post
    get "/sendlocation", to: "users#sendlocation"
    get "users/mail" => "users#mail"
    match 'users/sendmail' => 'users#sendmail', :as => :sendmail, via: :post
    match 'users/index' => 'users#index', :as => :index, via: :get
    root to: 'users#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Email_Notification/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Email_Notification/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

Email_Notification/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

Email_Notification/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  #Allows trusted parameters for signing up for an account
  def sign_up_params
    params.require(:user).permit(:name, :email, :location, :password, :password_confirmation)
  end

  #Allows trusted parameters for updating an account
  def account_update_params
    params.require(:user).permit(:name, :email, :location, :password, :password_confirmation,:current_password)
  end
end

Email_Notification/app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!


  def index
    @users=User.all
  end

#plucks out the the selected users in the checkbox and stores the emailid of the users in the email array,
#which will be used for sending email to those users.
  def mail
    if(params[:user_ids] && !params[:user_ids].empty?)
    user_ids = params[:user_ids].map{ |k| k.to_i }

    i=0
    $emails = []

    all_emails = User.all.pluck(:id, :email)
      user_ids.each do |user_id|

      all_emails.each do|all_email|
        if all_email[0]==user_id
              $emails[i] = all_email[1]
              i=i+1
        end
      end
    end
  print $emails
else
  redirect_to index_path, notice: "No user selected"
end
     #NotifMailer.new_notif.deliver_now
    #redirect_to index_path
end

# finds the email ids of the users based on the location
  def sendloc
    @location=params[:location].upcase
    $emails = []
    i=0
    all_emails = User.all.pluck(:location, :email)
    all_emails.each do|all_email|
      if all_email[0].upcase==@location
        $emails[i]=all_email[1]
        i=i+1
      end
    end
  end

# every user's email is selected and stored in the email array
  def sendall
    $emails = User.all.pluck(:email)
  end

# sends mail to the email ids stored in the email array
  def sendmail
    p=params[:p]
    q=params[:q]
    puts(p)
    $emails.each do |email|
      puts email
      NotifMailer.new_notif(q,p,email).deliver_now
    end
    redirect_to index_path, notice: "Email sent"
  end
 end

Email_Notification/app/helpers/application_helper.rb
module ApplicationHelper
end

Email_Notification/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mailer</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body class="<%= yield (:body_class) %>">
    <% if flash[:notice] %>
      <div class="notification is-success global-notification">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if flash[:alert] %>
    <div class="notification is-danger global-notification">
      <p class="alert"><%= alert %></p>
    </div>
    <% end %>
     <nav class="navbar is-warning" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <%= link_to root_path, class:"navbar-item" do %>
          <h1 class="title is-5">Mailer</h1>
        <% end  %>
      <div class="navbar-burger burger" data-target="navbar">
        <span></span>
        <span></span>
        <span></span>
      </div>
    </div>

      <div id="navbar" class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="field is-grouped">

            <% if user_signed_in? %>


              <div class="navbar-item has-dropdown is-hoverable">
                <%= link_to 'Account', edit_user_registration_path, class: "navbar-link" %>
                <div class="navbar-dropdown is-right">
                  <%= link_to current_user.name, edit_user_registration_path, class:"navbar-item" %>
                  <%= link_to "Log Out", destroy_user_session_path, method: :delete, class:"navbar-item" %>
                </div>
              </div>
            <% else %>

            <%= link_to "Sign In", new_user_session_path, class:"navbar-item button is-warning" %>
            <%= link_to "Sign up", new_user_registration_path, class:"navbar-item button is-warning"%>

            <% end %>

            </div>
          </div>
        </div>
    </div>
  </nav>

  <%= yield(:header) %>

  <div class="container">

    <%= yield %>

  </div>

  </body>
</html>

Email_Notification/app/views/users/index.html.erb
<% if @users != nil %>
  <% if @users.first.id ==current_user.id %>
  You are the Admin
    <%= form_tag mail_path({}) do %>
      <br>
        <table id="customers">
          <th> Name </th>
          <th> Location</th>
          <th> Email-Id </th>
          <th> Select  </th>

        <% @users.each do |user| %>

        <tr>

            <td><%= user.name%></td>

            <td><%= user.location%></td>

            <td><%= user.email %></td>

            <td>
                 <%= check_box_tag 'user_ids[]', user.id %>
            </td>
        </tr>


        <% end %>

        </table>
        <center>

        <div><%= submit_tag 'Send Email to Selected users' %></div>
        </center>
    <% end %>
 <%= link_to 'Send Email to All Users', sendall_path, class: 'button'%><br>
  <%= link_to 'Send Email based on their location', sendlocation_path, class: 'button'%>
  <% else %>
  <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                <div class="col-lg-10 align-self-end">
                    <h1 class="text-uppercase text-white font-weight-bold">Welcome, <%= current_user.name %></h1>
                    <hr class="divider my-4" />
                </div>
                <div class="col-lg-8 align-self-baseline">
                    <p class="text-white-75 font-weight-light mb-5">You are registered as a user in Mailer</p>
                </div>
            </div>
        </div>
    </header>
  <% end %>
<% end %>

Email_Notification/app/views/users/mail.html.erb
<%= form_tag sendmail_path({}) do |form| %>
<div class="field">
  <%= label_tag(:q, "Subject") %><br />
  <%= text_field_tag(:q) %>
</div>

<br>
<div class="field">
  <%= label_tag(:p, "Body") %><br />
  <div class="area">
    <%= text_area_tag :p, nil,  size: "25x10" %>
  </div>

</div>

  <p>
    <div><%= submit_tag 'Send Mail' %></div>
  </p>
<% end %>

Email_Notification/app/views/users/sendall.html.erb
Email to all the Users 

<%= form_tag sendmail_path({}) do |form| %>
<div class="field">
  <%= label_tag(:q, "Subject") %><br />
  <%= text_field_tag(:q) %>
</div>

<br>
<div class="field">
  <%= label_tag(:p, "Body") %><br />
  <div class="area">
    <%= text_area_tag :p, nil,  size: "25x10" %>
  </div>

</div>

  <p>
    <div><%= submit_tag 'Send Mail' %></div>
  </p>
<% end %>

Email_Notification/app/views/users/sendloc.html.erb
Send email to all users having location as <%= @location%>
<br/>
<%= form_tag sendmail_path({}) do |form| %>
<div class="field">
  <%= label_tag(:q, "Subject") %><br />
  <%= text_field_tag(:q) %>
</div>

<br>
<div class="field">
  <%= label_tag(:p, "Body") %><br />
  <div class="area">
    <%= text_area_tag :p, nil,  size: "25x10" %>
  </div>

</div>

  <p>
    <div><%= submit_tag 'Send Mail' %></div>
  </p>
<% end %>

Email_Notification/app/views/users/sendlocation.html.erb
<%= form_tag sendloc_path({}) do |form| %>
<div class="field">
  <%= label_tag(:location, "Location") %><br />
  <%= text_field_tag(:location) %>
</div>

  <p>
    <div><%= submit_tag 'Send Mail' %></div>
  </p>
<% end %>

Email_Notification/app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

Email_Notification/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>